### ISSUE TITLE
Ubuntu 16.04测试卡住。

### ISSUE THREAD

**Issue by xiaoyuvps** [aimkiray/op-script#1]
Ubuntu 16.04 默认自带python3.5

安装一切顺利。

跑到执行的时候就卡住了

最后应该是返回超时

**Comment by aimkiray** [comment]
root 用户要加上 --no-sandbox 关闭沙箱才能启动，新版 chrome 如是说。

我是在 Windows 测试的（吐槽你就输了XD），所以没问题。

指南 & code 稍后更新。
