### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by epicchaos** [aimkiray/op-script#2]
执行python OneProvider.py后 出现错误
Traceback (most recent call last):
  File "OneProvider.py", line 141, in <module>
    token = get_token()
  File "OneProvider.py", line 86, in get_token
    vm_id = soup_vm_id.find('input', attrs={'name': 'vm_id'})['value']
TypeError: 'NoneType' object is not subscriptable

**Comment by aimkiray** [comment]
好像 anti-bot 又回来了。。

anti-bot 分支：
pull（更新）一下 code，把 requests_mode 设置为 False（默认）。

master 分支：
切换 anti-bot 分支。

**Comment by epicchaos** [comment]
大佬 辛苦了(｡･∀･)ﾉﾞ

**Comment by aimkiray** [comment]
ω・´) 承让承让，还有指南也更新了。不过只测试了登陆。。
